import Foundation

/// How a Shot obtains its own Dock identity.
///
/// This axis is orthogonal to `IsolationStrategy` (which controls *data*
/// separation). Determined empirically during the M0 spike — see
/// `docs/mechanism.md` for the measurements behind each case.
public enum LaunchMode: String, Codable, CaseIterable, Sendable {
    /// Symlink farm: the wrapper mirrors the target's `Contents/` with symlinks
    /// and execs a symlink to the target binary that lives *inside* the wrapper.
    /// Survives target updates because nothing is copied.
    ///
    /// Only suitable for apps that do not spawn helper subprocesses. Both
    /// Chromium and Electron apps fail: their helpers resolve the framework
    /// through the target's real path, which the seatbelt sandbox denies once
    /// the main bundle is the wrapper. Measured on macOS 26.6 — see
    /// `docs/mechanism.md`.
    case link

    /// APFS copy-on-write clone of the target bundle with a patched Info.plist.
    /// The default: separate identity, works for every app family tested,
    /// costs ~0 bytes and under a second, but is pinned to the target's version
    /// at creation time (Doppio detects the drift and offers to regenerate).
    case clone

    /// Exec the target's real binary in place. Always works and always survives
    /// updates, but the instance is attributed to the *original* app, so it
    /// shares the original's Dock tile and name.
    case direct

    public var title: String {
        switch self {
        case .link:   return "Linked"
        case .clone:  return "Cloned"
        case .direct: return "Direct"
        }
    }

    public var explanation: String {
        switch self {
        case .link:
            return "Own Dock icon and name, and nothing is copied, so the Shot survives app updates. Does not work for Chromium or Electron apps."
        case .clone:
            return "Own Dock icon and name. Uses a copy-on-write clone (instant, no extra disk space). Needs regenerating when the original app updates."
        case .direct:
            return "Runs a second instance with separate data, but shares the original app's Dock icon and name."
        }
    }

    /// True when the Shot appears in the Dock as its own application.
    public var hasOwnIdentity: Bool { self != .direct }
}

/// How a Shot's data is kept separate from the original app's.
public enum IsolationStrategy: String, Codable, CaseIterable, Sendable {
    case chromium
    case electron
    case firefox
    case home
    case env
    case none

    public var title: String {
        switch self {
        case .chromium: return "Chromium profile"
        case .electron: return "Electron user data"
        case .firefox:  return "Firefox profile"
        case .home:     return "Home directory override"
        case .env:      return "Environment variables"
        case .none:     return "Shared data"
        }
    }

    public var isolatesData: Bool { self != .none }
}

/// What a Shot points at.
public enum ShotMode: String, Codable, CaseIterable, Sendable {
    case app
    case web
    case file
}

/// A single launcher generated by Doppio.
public struct Shot: Codable, Identifiable, Hashable, Sendable {
    public var id: UUID
    public var name: String
    public var mode: ShotMode
    public var launchMode: LaunchMode
    public var strategy: IsolationStrategy

    /// Bundle identifier of the target application (app / file modes).
    public var targetBundleID: String?
    /// Last known path of the target, used as a fallback when the bundle ID
    /// lookup fails. Never the primary source of truth.
    public var targetPath: String?
    /// URL for web-mode Shots.
    public var url: String?
    /// Document opened by file-mode Shots.
    public var documentPath: String?

    public var dataDir: String
    public var args: [String]
    public var env: [String: String]
    public var homeOverride: Bool
    public var ephemeral: Bool
    public var statusItem: Bool
    public var appearance: Appearance
    public var iconTint: String?
    public var iconBadge: String?
    public var createdAt: Date
    public var stubVersion: String

    /// Only `light` is expressible. `NSRequiresAquaSystemAppearance` can force
    /// light appearance but cannot force dark — setting it to false is simply
    /// the default — so a "dark" option would silently do nothing and is not
    /// offered. Existing Shots that stored `dark` still decode, and behave as
    /// `system`.
    public enum Appearance: String, Codable, CaseIterable, Sendable {
        case system, light, dark

        /// The options worth showing a user.
        public static var selectable: [Appearance] { [.system, .light] }

        public var title: String {
            switch self {
            case .system: return "System"
            case .light:  return "Always light"
            case .dark:   return "Dark (not supported by macOS for this)"
            }
        }
    }

    public init(
        id: UUID = UUID(),
        name: String,
        mode: ShotMode = .app,
        launchMode: LaunchMode = .link,
        strategy: IsolationStrategy = .none,
        targetBundleID: String? = nil,
        targetPath: String? = nil,
        url: String? = nil,
        documentPath: String? = nil,
        dataDir: String? = nil,
        args: [String] = [],
        env: [String: String] = [:],
        homeOverride: Bool = false,
        ephemeral: Bool = false,
        statusItem: Bool = false,
        appearance: Appearance = .system,
        iconTint: String? = nil,
        iconBadge: String? = nil,
        createdAt: Date = Date(),
        stubVersion: String = DoppioPaths.stubVersion
    ) {
        self.id = id
        self.name = name
        self.mode = mode
        self.launchMode = launchMode
        self.strategy = strategy
        self.targetBundleID = targetBundleID
        self.targetPath = targetPath
        self.url = url
        self.documentPath = documentPath
        self.dataDir = dataDir ?? DoppioPaths.defaultDataDir(for: id).path
        self.args = args
        self.env = env
        self.homeOverride = homeOverride
        self.ephemeral = ephemeral
        self.statusItem = statusItem
        self.appearance = appearance
        self.iconTint = iconTint
        self.iconBadge = iconBadge
        self.createdAt = createdAt
        self.stubVersion = stubVersion
    }

    /// Bundle identifier assigned to the generated wrapper.
    public var wrapperBundleID: String {
        "org.doppio-mac.shot.\(id.uuidString.lowercased())"
    }

    /// Filesystem location of the generated `.app`.
    ///
    /// Built from `fileSafeName`, never from `name` directly: a name containing
    /// `../..` would otherwise resolve outside the Shots directory and aim
    /// Doppio's recursive delete at a real application.
    public var bundleURL: URL {
        DoppioPaths.shotsDirectory.appendingPathComponent("\(fileSafeName).app")
    }

    public var dataDirURL: URL { URL(fileURLWithPath: dataDir) }
}
